use multiple gateways to fetch data
nonebot/nb-cli pull request #4
Opened 2021-04-30 04:18 UTC by StarHeartHunt

2021-04-30 04:58 UTC, yanyongyu requested changes

2021-04-30 04:58 UTC, yanyongyu commented on nb_cli/handlers/adapter.py
>  from cookiecutter.main import cookiecutter
```suggestion
from cookiecutter.main import cookiecutter
from concurrent.futures import ThreadPoolExecutor, as_completed
```

2021-04-30 04:58 UTC, yanyongyu commented on nb_cli/handlers/adapter.py
> +    ]
```suggestion
    urls = [
        "https://v2.nonebot.dev/adapters.json",
        "https://nonebot2-vercel-mirror.vercel.app/adapters.json",
        "https://cdn.jsdelivr.net/gh/nonebot/nonebot2/docs/.vuepress/public/adapters.json"
    ]
```

2021-04-30 04:58 UTC, yanyongyu commented on nb_cli/handlers/adapter.py
>      return list(map(lambda x: Adapter(**x), adapters))
```suggestion
    with ThreadPoolExecutor(max_workers=5) as executor:
        tasks = [executor.submit(httpx.get, url) for url in urls]

        for future in as_completed(tasks):
            try:
                resp = future.result()
                adapters = resp.json()
                break
            except httpx.RequestError as e:
                click.secho(
                    f"An error occurred while requesting {e.request.url}.",
                    fg="red")

    return list(map(lambda x: Adapter(**x), adapters))
```

2021-04-30 04:58 UTC, yanyongyu commented on nb_cli/handlers/plugin.py
>  from cookiecutter.main import cookiecutter
```suggestion
from cookiecutter.main import cookiecutter
from concurrent.futures import ThreadPoolExecutor, as_completed
```

2021-04-30 04:58 UTC, yanyongyu commented on nb_cli/handlers/plugin.py
>      return list(map(lambda x: Plugin(**x), plugins))
```suggestion
    urls = [
        "https://v2.nonebot.dev/plugins.json",
        "https://nonebot2-vercel-mirror.vercel.app/plugins.json",
        "https://cdn.jsdelivr.net/gh/nonebot/nonebot2/docs/.vuepress/public/plugins.json"
    ]
    with ThreadPoolExecutor(max_workers=5) as executor:
        tasks = [executor.submit(httpx.get, url) for url in urls]

        for future in as_completed(tasks):
            try:
                resp = future.result()
                plugins = resp.json()
                break
            except httpx.RequestError as e:
                click.secho(
                    f"An error occurred while requesting {e.request.url}.",
                    fg="red")

    return list(map(lambda x: Plugin(**x), plugins))
```

2021-04-30 07:04 UTC, StarHeartHunt commented
7d84c7d
跑了一下，应该没问题

2021-05-01 02:39 UTC, yanyongyu approved these changes

2021-05-01 02:40 UTC, merged